# Generated by Django 6.0.4 on 2026-06-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providerprofile',
            table=None,
        ),
    ]
