# Generated by Django 6.0.4 on 2026-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_providerprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providerprofile',
            table='provider_profile',
        ),
    ]
